const express = require('express');
const router = express.Router();
const { getReviews, getAllReviews, addReview, approveReview, deleteReview } = require('../controllers/reviewController');
const { protect } = require('../middleware/auth');
router.get('/', getReviews);
router.get('/all', protect, getAllReviews);
router.post('/', addReview);
router.put('/:id/approve', protect, approveReview);
router.delete('/:id', protect, deleteReview);
module.exports = router;
